### ISSUE TITLE
Build fails with lots of undefined functions despite following build instructions

### ISSUE THREAD

**Issue by ProfessorLongBeard** [kiznit/rainbow-os#3] opened 2024-08-21 19:19 UTC

**Comment by kiznit** [comment] 2024-08-21 19:33
If you want help with this, you are going to have to provide some information and logs. The code compile just fine for me.

**Comment by ProfessorLongBeard** [comment] 2024-08-22 02:59
> If you want help with this, you are going to have to provide some information and logs. The code compile just fine for me.

I get about 96% into the build and end up with this error:

`[ 96%] Building CXX object unittest/CMakeFiles/unittest.dir/unittest.cpp.o
In file included from /usr/include/signal.h:328,
                 from /media/austin/Scratch/rainbow-os/third_party/catch2/catch.hpp:8034,
                 from /media/austin/Scratch/rainbow-os/unittest/unittest.hpp:29,
                 from /media/austin/Scratch/rainbow-os/unittest/unittest.cpp:28:
/media/austin/Scratch/rainbow-os/third_party/catch2/catch.hpp:10822:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
10822 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/c++/13/bits/atomic_wait.h:45,
                 from /usr/include/c++/13/bits/atomic_base.h:42,
                 from /usr/include/c++/13/bits/shared_ptr_atomic.h:33,
                 from /usr/include/c++/13/memory:81,
                 from /media/austin/Scratch/rainbow-os/third_party/catch2/catch.hpp:2943:
/usr/include/unistd.h:640:17: note: ‘long int sysconf(int)’ declared here
  640 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
/media/austin/Scratch/rainbow-os/third_party/catch2/catch.hpp:10881:45: error: size of array ‘altStackMem’ is not an integral constant-expression
10881 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |                                             ^~~~~~~~~~~~
make[2]: *** [unittest/CMakeFiles/unittest.dir/build.make:76: unittest/CMakeFiles/unittest.dir/unittest.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:558: unittest/CMakeFiles/unittest.dir/all] Error 2
make: *** [Makefile:101: all] Error 2
`

I didn't seem to run into undefined functions this time shockingly

**Comment by ProfessorLongBeard** [comment] 2024-08-22 03:01
It seems to just be the ARM64 build that fails with undefined functions

```
[100%] Linking CXX executable bootaa64.efi
lld-link: error: undefined symbol: class mtl::LogSystem mtl::g_log
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(unsigned __int64 __cdecl AllocatePages(unsigned __int64, enum efi::MemoryType))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(unsigned __int64 __cdecl AllocatePages(unsigned __int64, enum efi::MemoryType))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class std::shared_ptr<class Console> __cdecl InitializeConsole(struct efi::SystemTable *))
>>> referenced 91 more times

lld-link: error: undefined symbol: public: struct mtl::LogRecord __cdecl mtl::LogSystem::CreateRecord(enum mtl::LogSeverity)
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(unsigned __int64 __cdecl AllocatePages(unsigned __int64, enum efi::MemoryType))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class std::vector<class GraphicsDisplay> __cdecl InitializeDisplays(class efi::BootServices *))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class std::vector<class GraphicsDisplay> __cdecl InitializeDisplays(class efi::BootServices *))
>>> referenced 40 more times

lld-link: error: undefined symbol: public: __cdecl mtl::LogStream::LogStream(struct mtl::LogRecord &)
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(unsigned __int64 __cdecl AllocatePages(unsigned __int64, enum efi::MemoryType))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class std::vector<class GraphicsDisplay> __cdecl InitializeDisplays(class efi::BootServices *))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class std::vector<class GraphicsDisplay> __cdecl InitializeDisplays(class efi::BootServices *))
>>> referenced 40 more times

lld-link: error: undefined symbol: strlen
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(unsigned __int64 __cdecl AllocatePages(unsigned __int64, enum efi::MemoryType))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class std::vector<class GraphicsDisplay> __cdecl InitializeDisplays(class efi::BootServices *))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class std::vector<class GraphicsDisplay> __cdecl InitializeDisplays(class efi::BootServices *))
>>> referenced 60 more times

lld-link: error: undefined symbol: public: void __cdecl mtl::LogStream::Write(class std::basic_string_view<char>)
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(unsigned __int64 __cdecl AllocatePages(unsigned __int64, enum efi::MemoryType))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class std::vector<class GraphicsDisplay> __cdecl InitializeDisplays(class efi::BootServices *))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class std::vector<class GraphicsDisplay> __cdecl InitializeDisplays(class efi::BootServices *))
>>> referenced 59 more times

lld-link: error: undefined symbol: public: void __cdecl mtl::LogStream::Flush(void)
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(unsigned __int64 __cdecl AllocatePages(unsigned __int64, enum efi::MemoryType))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class std::vector<class GraphicsDisplay> __cdecl InitializeDisplays(class efi::BootServices *))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class std::vector<class GraphicsDisplay> __cdecl InitializeDisplays(class efi::BootServices *))
>>> referenced 40 more times

lld-link: error: undefined symbol: public: void __cdecl mtl::LogSystem::PushRecord(struct mtl::LogRecord &&)
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(unsigned __int64 __cdecl AllocatePages(unsigned __int64, enum efi::MemoryType))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class std::vector<class GraphicsDisplay> __cdecl InitializeDisplays(class efi::BootServices *))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class std::vector<class GraphicsDisplay> __cdecl InitializeDisplays(class efi::BootServices *))
>>> referenced 40 more times

lld-link: error: undefined symbol: abort
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(unsigned __int64 __cdecl AllocatePages(unsigned __int64, enum efi::MemoryType))
>>> referenced by CMakeFiles/boot.dir/runtime/malloc.cpp.obj:(malloc)
>>> referenced by CMakeFiles/boot.dir/runtime/malloc.cpp.obj:(free)
>>> referenced 6 more times

lld-link: error: undefined symbol: _assert
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class std::vector<class GraphicsDisplay> __cdecl InitializeDisplays(class efi::BootServices *))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class kz::expected<struct Module, enum efi::Status> __cdecl LoadModule(struct efi::FileProtocol *, class std::basic_string_view<char>, enum efi::MemoryType))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class kz::expected<class std::shared_ptr<class MemoryMap>, enum efi::Status> __cdecl ExitBootServices(void *, struct efi::SystemTable *))
>>> referenced 62 more times

lld-link: error: undefined symbol: memset
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(unsigned __int64 __cdecl AllocateZeroedPages(unsigned __int64, enum efi::MemoryType))
>>> referenced by CMakeFiles/boot.dir/elf.cpp.obj:(void * __cdecl ElfLoad(struct Module const &, class PageTable &))
>>> referenced by CMakeFiles/boot.dir/runtime/malloc.cpp.obj:(calloc)
>>> referenced 1 more times

lld-link: error: undefined symbol: void * __cdecl operator new(unsigned __int64)
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class std::shared_ptr<class Console> __cdecl InitializeConsole(struct efi::SystemTable *))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class kz::expected<class std::shared_ptr<class LogFile>, enum efi::Status> __cdecl InitializeLogFile(struct efi::FileProtocol *))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class kz::expected<class std::shared_ptr<class MemoryMap>, enum efi::Status> __cdecl ExitBootServices(void *, struct efi::SystemTable *))
>>> referenced 7 more times

lld-link: error: undefined symbol: public: void __cdecl mtl::LogSystem::AddLogger(class std::shared_ptr<class mtl::Logger>)
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class std::shared_ptr<class Console> __cdecl InitializeConsole(struct efi::SystemTable *))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class kz::expected<class std::shared_ptr<class LogFile>, enum efi::Status> __cdecl InitializeLogFile(struct efi::FileProtocol *))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(enum efi::Status __cdecl Boot(void *, struct efi::SystemTable *))

lld-link: error: undefined symbol: public: void __cdecl mtl::LogStream::WriteHex(unsigned __int64, unsigned __int64)
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class std::vector<class GraphicsDisplay> __cdecl InitializeDisplays(class efi::BootServices *))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class kz::expected<struct efi::FileProtocol *, enum efi::Status> __cdecl InitializeFileSystem(void *, class efi::BootServices *))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class kz::expected<struct efi::FileProtocol *, enum efi::Status> __cdecl InitializeFileSystem(void *, class efi::BootServices *))
>>> referenced 24 more times

lld-link: error: undefined symbol: public: void __cdecl mtl::LogStream::Write(unsigned int, bool)
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class std::vector<class GraphicsDisplay> __cdecl InitializeDisplays(class efi::BootServices *))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class std::vector<class GraphicsDisplay> __cdecl InitializeDisplays(class efi::BootServices *))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class std::vector<class GraphicsDisplay> __cdecl InitializeDisplays(class efi::BootServices *))
>>> referenced 7 more times

lld-link: error: undefined symbol: public: void __cdecl mtl::LogStream::Write(class std::basic_string_view<char16_t>)
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class kz::expected<struct Module, enum efi::Status> __cdecl LoadModule(struct efi::FileProtocol *, class std::basic_string_view<char>, enum efi::MemoryType))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class kz::expected<struct Module, enum efi::Status> __cdecl LoadModule(struct efi::FileProtocol *, class std::basic_string_view<char>, enum efi::MemoryType))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class kz::expected<struct Module, enum efi::Status> __cdecl LoadModule(struct efi::FileProtocol *, class std::basic_string_view<char>, enum efi::MemoryType))
>>> referenced 1 more times

lld-link: error: undefined symbol: public: void __cdecl mtl::LogSystem::RemoveLogger(class std::shared_ptr<class mtl::Logger> const &)
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class kz::expected<class std::shared_ptr<class MemoryMap>, enum efi::Status> __cdecl ExitBootServices(void *, struct efi::SystemTable *))
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(class kz::expected<class std::shared_ptr<class MemoryMap>, enum efi::Status> __cdecl ExitBootServices(void *, struct efi::SystemTable *))

lld-link: error: undefined symbol: public: void __cdecl mtl::LogStream::Write(unsigned __int64, bool)
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(enum efi::Status __cdecl Boot(void *, struct efi::SystemTable *))

lld-link: error: undefined symbol: public: __cdecl mtl::SimpleDisplay::SimpleDisplay(class std::shared_ptr<class mtl::Surface>, class std::shared_ptr<class mtl::Surface>)
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(enum efi::Status __cdecl Boot(void *, struct efi::SystemTable *))

lld-link: error: undefined symbol: public: __cdecl mtl::GraphicsConsole::GraphicsConsole(class std::shared_ptr<class mtl::IDisplay>)
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(enum efi::Status __cdecl Boot(void *, struct efi::SystemTable *))

lld-link: error: undefined symbol: public: void __cdecl mtl::GraphicsConsole::Clear(void)
>>> referenced by CMakeFiles/boot.dir/boot.cpp.obj:(enum efi::Status __cdecl Boot(void *, struct efi::SystemTable *))

lld-link: error: too many errors emitted, stopping now (use /errorlimit:0 to see all errors)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [src/CMakeFiles/boot.dir/build.make:262: src/bootaa64.efi] Error 1
make[4]: *** [CMakeFiles/Makefile2:147: src/CMakeFiles/boot.dir/all] Error 2
make[3]: *** [Makefile:91: all] Error 2
make[2]: *** [CMakeFiles/external_boot.dir/build.make:95: boot/src/external_boot-stamp/external_boot-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:242: CMakeFiles/external_boot.dir/all] Error 2
make: *** [Makefile:101: all] Error 2

```

**Comment by kiznit** [comment] 2024-08-22 03:11
On x86_64, this appears to be a problem with the catch library used for unit tests. Maybe it just needs to be updated / configured.

What platform and compiler + version are you using to build this?

**Comment by kiznit** [comment] 2024-08-22 03:13
For arm64, I am confused. If you check the build pipelines, it works fine for a number of configurations:
https://github.com/kiznit/rainbow-os/actions/runs/6961621964

What cmake command did you use to generate the makefiles?

**Comment by kiznit** [comment] 2024-08-22 03:16
I just realized the above are for the dev branch, let me see if I can trigger the build pipelines for master. I am assuming you are using master?

**Comment by ProfessorLongBeard** [comment] 2024-08-22 03:21
> On x86_64, this appears to be a problem with the catch library used for unit tests. Maybe it just needs to be updated / configured.
> 
> What platform and compiler + version are you using to build this?

I'm on x86_64 using I believe the host clang compiler (assuming that's what the source was configured to use)...



> For arm64, I am confused. If you check the build pipelines, it works fine for a number of configurations: https://github.com/kiznit/rainbow-os/actions/runs/6961621964
> 
> ![image](https://private-user-images.githubusercontent.com/8992950/360237028-64272e00-db55-461c-a9c1-f39360405286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyOTcwMjcsIm5iZiI6MTcyNDI5NjcyNywicGF0aCI6Ii84OTkyOTUwLzM2MDIzNzAyOC02NDI3MmUwMC1kYjU1LTQ2MWMtYTljMS1mMzkzNjA0MDUyODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjJUMDMxODQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGYyZjczNWEwMmE3YjA3MTAwZjVmZDMwNjgxZTcyZTlhMDgxOTI1NzcyYTQ4ODQ3MTRmMGIyNjY4MTEzMWJiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nGAkTCiO_3Wp-tjqldeM8bxXhAUYjF8UWDjZreYrsmg)
> 
> What cmake command did you use to generate the makefiles?

austin@ryzen-beast:/media/austin/Scratch/rainbow-os/build$ cmake -DARCH=aarch64 .. (for x86_64 I omitted the ARM64 arch)



> I just realized the above are for the dev branch, let me see if I can trigger the build pipelines for master. I am assuming you are using master?

Yes I believe so I didn't look to see the dev branch at all... That might of been my issue haha

**Comment by kiznit** [comment] 2024-08-22 03:23
The master branch appears to build correctly as well, see https://github.com/kiznit/rainbow-os/actions/runs/10501256654

**Comment by kiznit** [comment] 2024-08-22 03:24
What OS / distribution are you using?

Can you check what "clang --version" returns?

**Comment by ProfessorLongBeard** [comment] 2024-08-22 03:26
> What OS / distribution are you using?
> 
> Can you check what "clang --version" returns?

I'm using Linux Mint 22

Here's my clang information:

austin@ryzen-beast:/media/austin/Scratch/rainbow-os/build$ clang --version
Ubuntu clang version 18.1.3 (1ubuntu1)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
austin@ryzen-beast:/media/austin/Scratch/rainbow-os/build$

**Comment by ProfessorLongBeard** [comment] 2024-08-22 03:27
> The master branch appears to build correctly as well, see https://github.com/kiznit/rainbow-os/actions/runs/10501256654

I wonder if it's just how my host is configured then...

**Comment by kiznit** [comment] 2024-08-22 03:30
> I wonder if it's just how my host is configured then...

I think the unit tests problem has to do with the catch2 library not working on mint 22. That library is likely out of date by now.

As for the arm64 build, I am not sure just yet. But I don't think I've ever tested clang-18 and something might have changed there where its not detecting the platform correctly.

I don't have time tonight to look into this but should be able to over the next few days.

**Comment by ProfessorLongBeard** [comment] 2024-08-22 03:35
> > I wonder if it's just how my host is configured then...
> 
> I think the unit tests problem has to do with the catch2 library not working on mint 22. That library is likely out of date by now.
> 
> As for the arm64 build, I am not sure just yet. But I don't think I've ever tested clang-18 and something might have changed there where its not detecting the platform correctly.
> 
> I don't have time tonight to look into this but should be able to over the next few days.

Sounds good! I'll see if I can't get a newer version of the library on my system as well

**Comment by kiznit** [comment] 2024-08-22 04:42
I updated the workflows to use clang-18 and I got green builds, so we can rule this one out.
https://github.com/kiznit/rainbow-os/actions/runs/10501941355

**Comment by kiznit** [comment] 2024-08-22 04:48
Updating the workflows to use ubuntu-latest instead of ubuntu-20 seems to have reproduced the arm64 build problems:
https://github.com/kiznit/rainbow-os/actions/runs/10501981773

**Comment by kiznit** [comment] 2024-08-22 19:01
The unit test build failure on x64 has been fixed.

**Comment by kiznit** [comment] 2024-08-23 03:29
I think the build errors on aarch64 are happening because one doesn't have llvm-ar and llvm-ranlib installed. These don't happen for me, but I am pretty I installed llvm before.

Can you try installing llvm-18 to go with your clang-18 and see if that helps?

**Comment by ProfessorLongBeard** [comment] 2024-08-23 04:19
> I think the build errors on aarch64 are happening because one doesn't have llvm-ar and llvm-ranlib installed. These don't happen for me, but I am pretty I installed llvm before.
> 
> Can you try installing llvm-18 to go with your clang-18 and see if that helps?

Yes I can do that

**Comment by ProfessorLongBeard** [comment] 2024-08-23 04:20
It seems I have llvm-18 already installed...

**Comment by kiznit** [comment] 2024-08-23 04:32
I fixed the github workflow file and now it can compile clang-16/clang-18/ubuntu 20/ubuntu 22.

I think there might be a problem with your compiler setup. What do you get when you run "lld-link --version"?

**Comment by kiznit** [comment] 2024-08-23 04:40
I've seen your error log when its using "ar" and "ranlib" to build the static library (instead of the proper "llvm-ar" and "llvm-ranlib". This was happening because these where not properly linked.

This fixed the issue on github:
       sudo update-alternatives --install /usr/local/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-18 100
       sudo update-alternatives --install /usr/local/bin/llvm-ranlib llvm-ranlib /usr/bin/llvm-ranlib-18 100

**Comment by kiznit** [comment] 2024-08-23 16:42
I can repro the problem by romiving llvm-ar and llvm-ranlib from my path. cmake then cannot find them and fall back on ar / ranlib and that cause these errors.

**Comment by ProfessorLongBeard** [comment] 2024-08-23 18:52
> I can repro the problem by removing llvm-ar and llvm-ranlib from my path. cmake then cannot find them and falls back on ar / ranlib. This causes unresolved external errors when trying to link the bootloader (and presumably the kernel).

Ahh I see! It seems it was an issue with my compiler setup then

**Comment by kiznit** [comment] 2024-08-23 20:11
I will close this issue, but feel free to re-open it if you need more help.

**Closed by kiznit** 2024-08-23 20:11 UTC

**Comment by ProfessorLongBeard** [comment] 2024-08-24 00:25
> The master branch currently compiles successfully on Ubuntu 20 and 22 using clang 16 or clang 18, see https://github.com/kiznit/rainbow-os/actions/runs/10520042475
> 
> I will close this issue, but feel free to re-open it if you need more help.

Will do good sir! Thank you for your help!
